# Generated by Django 4.2.9 on 2024-01-23 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
